// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijryimfyqqnpongewpfu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqcnlpbWZ5cXFucG9uZ2V3cGZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNzgzNTcsImV4cCI6MjA2OTY1NDM1N30.PTIFc4bRgUvlc-iDTOTTIh7efxPNBx0T_uLlxUSICZ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});